// Language message arrays
const messages = {
    en: {
        title_login: "Login",
        title_signup: "Sign Up",
        get title() { return this[`title_${funcName}`]; },
        username_label: "Username:",
        password_label: "Password: (Length: $length)",
        show_password_label: "Show Password",
        get submit_btn() { return this.title; },
        success: "Sign Up succeed. Wait 90s to login (200)",
        success2: "Registration Successful. Waiting...",
        passwd_weak: "Weak",
        passwd_medium: "Medium",
        passwd_strong: "Strong",
        error_status: "Error $status:$extraCode",
        invalid_username_format: "Username must start with a letter, use only letters, numbers, hyphens, or underscores",
        invalid_username_length: "Username must be 8–20 characters",
        invalid_password: "Password processing failed",
        password_too_short: "Password must be at least 14 characters",
        invalid_password_chars: "Password must use only standard ASCII characters (space to })",
        password_repeating_chars: "Password must not contain the same character repeated 3 times",
        password_sequence_chars: "Password must not contain character sequences like abc, 123 or cba",
        password_module_not_loaded: "Password processing module not loaded",
        password_calc_failed: "Password processing failed",
        error_get_signup_session: "Network error, can't load signup_session",
        too_more_tries: "Too more tries. Please retry later.",
        save_password_label: "Allow browser to save password"
    },
    cn: {
        title_login: "登录",
        title_signup: "注册",
        get title() { return this[`title_${funcName}`]; },
        username_label: "用户名：",
        password_label: "密码：（长度：$length）",
        show_password_label: "显示密码",
        get submit_btn() { return this.title; },
        success: "注册成功，等待90秒登录 (200)",
        success2: "注册成功。请稍候。",
        passwd_weak: "密码太弱",
        passwd_medium: "密码一般",
        passwd_strong: "密码很强",
        error_status: "错误 $status:$extraCode",
        invalid_username_format: "用户名必须以字母开头，仅限字母、数字、连字符或下划线",
        invalid_username_length: "用户名必须为8-20字符",
        invalid_password: "密码处理失败",
        password_too_short: "密码必须至少14个字符",
        invalid_password_chars: "密码只能使用标准ASCII字符（空格到}）",
        password_repeating_chars: "密码不能包含连续三个相同字符",
        password_sequence_chars: "网络错误，无法加载 signup_session",
        password_module_not_loaded: "密码处理模块未加载",
        password_calc_failed: "密码计算失败",
        error_get_signup_session: "Network error, can't load signup_session",
        too_more_tries: "尝试次数过多。请稍后重试。",
        save_password_label: "是否允许浏览器保存密码"
    },
    ca: {
        title_login: "登入",
        title_signup: "註冊",
        get title() { return this[`title_${funcName}`]; },
        username_label: "用戶名：",
        password_label: "密碼：（長度：$length）",
        show_password_label: "顯示密碼",
        get submit_btn() { return this.title; },
        success: "註冊成功，等90秒登入 (200)",
        success2: "註册成功。请稍候。",
        passwd_weak: "密碼太弱",
        passwd_medium: "密碼一般",
        passwd_strong: "密碼很強",
        error_status: "錯誤 $status:$extraCode",
        invalid_username_format: "用戶名必須以字母開頭，只限字母、數字、連字符或下劃線",
        invalid_username_length: "用戶名必須為8-20字",
        invalid_password: "密碼處理失敗",
        password_too_short: "密碼必須至少14個字",
        invalid_password_chars: "密碼只能使用標準ASCII字符（空格到}）",
        password_repeating_chars: "密碼不能包含連續三個相同字符",
        password_sequence_chars: "網路錯誤，無法載入 signup_sessio",
        password_module_not_loaded: "密碼處理模組未加載",
        password_calc_failed: "密碼計算失敗",
        error_get_signup_session: "Network error, can't load signup_session",
        too_more_tries: "嘗試次數過多。請稍後重試。",
        save_password_label: "是否允許瀏覽器儲存密碼"
    }
};
